// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM9JuWnedO4IQKHqCBuF1ezK3BphYgMxQ',
    appId: '1:332038829917:web:fc11c20a0e7e4127739ab4',
    messagingSenderId: '332038829917',
    projectId: 'chatbot-83d39',
    authDomain: 'chatbot-83d39.firebaseapp.com',
    databaseURL: 'https://chatbot-83d39-default-rtdb.firebaseio.com',
    storageBucket: 'chatbot-83d39.appspot.com',
    measurementId: 'G-CJHQEB9N3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8nKH4U-iqPuqOOcAyoku_zWyinmx3Vn0',
    appId: '1:332038829917:android:99d1022d3e375e68739ab4',
    messagingSenderId: '332038829917',
    projectId: 'chatbot-83d39',
    databaseURL: 'https://chatbot-83d39-default-rtdb.firebaseio.com',
    storageBucket: 'chatbot-83d39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7KldUpXgdzdvkiAyckDdViUIroXpBvB0',
    appId: '1:332038829917:ios:fca381efd98ce79e739ab4',
    messagingSenderId: '332038829917',
    projectId: 'chatbot-83d39',
    databaseURL: 'https://chatbot-83d39-default-rtdb.firebaseio.com',
    storageBucket: 'chatbot-83d39.appspot.com',
    iosClientId: '332038829917-jnhgio58hbdf1p82p7eoio7f8ifsnu4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
